### ISSUE TITLE
Register a user account

### ISSUE THREAD

**Issue by BenCheng2** [CSC207-2022F-UofT/course-project-group-71#10]
The user chooses the type of user account and enter information for account registeration.

**Comment by BenCheng2** [comment]
User enter the username, the password, and re-enter password
Check if the username exists
Check if two passwords are equal to each other
Check if the the password are valid
The account is now usable
Show success view if finished, show failure view if failed in one of the checks

**Comment by AllysonCui** [comment]
add condition for password length

**Comment by AllysonCui** [comment]
can copy the use case for login

**Comment by AllysonCui** [comment]
Link with the login page

Login page being the first page, then a button to direct user to register page.

a button in register page to back to the login page

**Comment by AllysonCui** [comment]
changed the interface so it has the same style as login page

**Comment by Anita-hua** [comment]
The password can't be too short so it must be for example has a length greater than 5. And it cannot be too long as well so we have to set a maximum length of the password for example length of 20. Add the restriction to the password length. And the password can't be the exact same thing as the user_id otherwise it will not be safe.

**Comment by ChrisSong1** [comment]
Register a user account and reset new password are similar, They have to make sure that the password cannot be blank, and they have to be specific about the length and strength of the password.
