### ISSUE TITLE
Create an event

### ISSUE THREAD

**Issue by BenCheng2** [CSC207-2022F-UofT/course-project-group-71#4]
Ben is a planner of an event. He wants to add an event page on the software. He uses the event planner program and chooses to create a new event. He inputs the name and details of the event, and the program adds a page about this event to the database.

**Comment by BenCheng2** [comment]
An organization log in the account
Decide to create an new event
The system verify if it’s the organization
If yes, organization start to fill in information needed for the event
If event name existed, show failure
The event is put into the created event list of the organization
The event is put on the database of website and will show on the website now
Show success view
If failed in one of the checks, show failure view

**Comment by BenCheng2** [comment]
Need updates, as we removed image_path and event_type for event information so relatively the code should change

**Comment by Anita-hua** [comment]
After the event was created, it will stay unpublished until the organization publish the event. They can't publish the event straightly they still have to click the publish button in th unpublished event page view in order to publish the event and let other participants to see. Make sure we contain this note in either our documentation or README.

**Comment by AllysonCui** [comment]
After the event has been published, it will be removed from the unpublished page and be added to the upcoming event page. The event can also be searched up by the participant after being published.

**Comment by AllysonCui** [comment]
The event can also be searched up by the participant after being published.
